### ISSUE TITLE
Grpc connection

### ISSUE THREAD

**Issue by patiee** [patiee/juno-smart-contracts#3]
@bmorphism When I try to get contract info from grpc I got error:
```
rpc error: code = Unavailable desc = connection closed
```
Can you help me fix that? You can use `grpc-connection` branch for reproducing it

**Comment by bmorphism** [comment]
sure! @patiee would appreciate more details / context, ideally would like to have:

0. steps to arrive at desired state (could be in `README.md` "Getting Started" section, for instance)
1. the exact command you tried when the error occurred please
2. full log

**Comment by patiee** [comment]
Everything is working with grpc connection, just endpoint needs to be enabled inside node.
